In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download'
url = f'{prefix}/misc/taxi_zone_lookup.csv'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

In [5]:
df = pd.read_csv(url)

In [6]:
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [7]:
df.head(0)

Empty DataFrame
Columns: [LocationID, Borough, Zone, service_zone]
Index: []

In [12]:
df['service_zone']

0              EWR
1        Boro Zone
2        Boro Zone
3      Yellow Zone
4        Boro Zone
          ...
260    Yellow Zone
261    Yellow Zone
262    Yellow Zone
263            NaN
264            NaN
Name: service_zone, Length: 265, dtype: str

In [16]:
dtype = {
    "LocationID": "Int64",
    "Borough": "string",
    "Zone": "string",
    "service_zone": "string"
}

df = pd.read_csv(
    url,
    dtype=dtype,
)

In [17]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [18]:
df.head(0)

Empty DataFrame
Columns: [LocationID, Borough, Zone, service_zone]
Index: []

In [24]:
df.head(0).to_sql(
    name='taxi_zone_lookup',
    con=engine,
    if_exists='replace',
    index=False,
)

0

In [25]:
print(pd.io.sql.get_schema(df, name='taxi_zone_lookup', con=engine))

CREATE TABLE taxi_zone_lookup (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [26]:
len(df)

265

In [27]:
from tqdm.auto import tqdm

In [28]:
df.to_sql(
    name='taxi_zone_lookup',
    con=engine,
    if_exists='append',
    index=False,
)

-1